10 implement more cards
P1nkL1on/Gwent5 pull request #58
Opened 2023-07-06 20:51 UTC by IrizGem

Added some Northern dudes

2023-07-07 16:18 UTC, P1nkL1on requested changes
Офигенно! Много хороших карт реализовала. Выписал некоторые правки, подозрения и ошибки, которые нашел. Спасиба :3

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +        startChoiceToTargetCard(ally, enemy, this, randoms(cardsFiltered(ally, enemy, {isBronze}, EnemyDeckStarting), 3, ally.rng));
а вот тут хитрость. Трисс создает из ОБОИХ колод. т.е. нужно ввести ещё один инут EitherDeckStarting, в котором вместе их объединять

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +        startChoiceToTargetCard(ally, enemy, this, {isBronzeOrSilver}, AllyDiscard, 3);
```suggestion
        startChoiceToTargetCard(ally, enemy, this, {isBronzeOrSilver, isUnit}, AllyDiscard, 3);
```

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +        std::vector<Card *> cards = ally.row(rowAndPos.row());
```suggestion
        const std::vector<Card *> cards = ally.row(rowAndPos.row());
```

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +            setPower(card, power, ally, enemy, this);
её прям надо затестировать. у меня есть большое опасение, что если её выбить на отрицательную силу перед смертью типа -2, то она и себя посчитает среди меньших юнитов и всем поставит хп на -2.

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +        startChoiceToTargetCard(ally, enemy, this, {}, EnemyDeck);
```suggestion
        startChoiceToTargetCard(ally, enemy, this, {}, EnemyField);
```
не колода

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +        assert(false);
в ифах перед этим нужно поставить reutrn-ы, потому что сейчас карта ассертится в любом случае. можно было засмоктестить :)

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +        damage(random(cardsFiltered(ally, enemy, {}, EnemyBoard), ally.rng), 1, ally, enemy, this);
я думаю, что нужно добавить проверку, что требушет находится на поле. у меня небольшие соменения, и возможно эта штука вызывается (или будет вызываться) из деки, руки и пр

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +        int n = nCrewed(this, ally);
```suggestion
        int n = 1 + nCrewed(this, ally);
```
наверное на 1 больше, тк число nCrewed может быть 0

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +    };
сейчас в абилке получается бесконечный цикл. к тому же, и первый и второй урон будут увеличены от crewed.

2023-07-07 16:18 UTC, P1nkL1on commented on Cards/archieve.cpp
> +    };
```suggestion
    _onDeploy = [=](Field &ally, Field &enemy) {
        _damaged = false;
        startChoiceToTargetCard(ally, enemy, this, {}, EnemyBoard);
    };

    _onTargetChoosen = [=](Card *target, Field &ally, Field &enemy) {
        int x = 3 + _damaged * nCrewed(this, ally);
        if (_damaged)
            return;
            
        _damaged = true;
        if (damage(target, x, ally, enemy, this))
            startChoiceToTargetCard(ally, enemy, this, {otherThan(target)}, EnemyBoard);
    };
```

2023-07-10 17:43 UTC, IrizGem commented on Cards/archieve.cpp
> +            setPower(card, power, ally, enemy, this);
Нет, на это есть демка, и сыгранная в один ряд с двумя баллистами на 7 и 7+5 Сабрина с урона 5 делает две баллисты по 7, а не по -2.

2023-07-10 17:50 UTC, IrizGem commented on Cards/archieve.cpp
> +        int n = nCrewed(this, ally);
Переделала метод nCrewed, теперь он действительно может быть 0

2023-07-10 17:53 UTC, IrizGem commented on Cards/archieve.cpp
> +    };
Ну, потому что я так поняла эту абилку)

2023-07-11 12:50 UTC, P1nkL1on approved these changes

2023-07-11 12:50 UTC, merged